# Font
font_family      FuraCode Nerd Font
bold_font        FuraCode Nerd Font Medium
italic_font      FuraCode Nerd Font Italic
bold_italic_font FuraCode Nerd Font Medium Italic

# Font size
font_size 14.0

# Multi-character ligatures
disable_ligatures cursor

# Sync screen updates to refresh rate of monitor
sync_to_monitor yes

# Window request attention on bell
window_alert_on_bell yes

# Disable audio bell
enable_audio_bell no

# Disable bell symbol on tab
bell_on_tab no

# Color of kitty window's titlebar
wayland_titlebar_color system

# Window size
remember_window_size  no
initial_window_width  1225
initial_window_height 475

# Open new tab on same directory
map ctrl+shift+t new_tab_with_cwd

# Tab bar style
tab_bar_style separator
tab_separator " "

# Open new window on same directory
map ctrl+shift+enter new_window_with_cwd

# Switch focus to the neighboring window
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right

# Resize window
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter 3
map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+home resize_window reset

# Kitty theme - Frappe savour
# The basic colors
foreground              #4C4F69
background              #EFF1F5
selection_foreground    #EFF1F5
selection_background    #DC8A78

# Cursor colors
cursor                  #DC8A78
cursor_text_color       #EFF1F5

# URL underline color when hovering with mouse
url_color               #DC8A78

# Kitty window border colors
active_border_color     #7287FD
inactive_border_color   #9CA0B0
bell_border_color       #DF8E1D

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #EFF1F5
active_tab_background   #8839EF
inactive_tab_foreground #4C4F69
inactive_tab_background #9CA0B0
tab_bar_background      #BCC0CC

# Colors for marks (marked text in the terminal)
mark1_foreground #EFF1F5
mark1_background #7287fD
mark2_foreground #EFF1F5
mark2_background #8839EF
mark3_foreground #EFF1F5
mark3_background #209FB5

# The 16 terminal colors

# black
color0 #5C5F77
color8 #6C6F85

# red
color1 #D20F39
color9 #D20F39

# green
color2  #40A02B
color10 #40A02B

# yellow
color3  #DF8E1D
color11 #DF8E1D

# blue
color4  #1E66F5
color12 #1E66F5

# magenta
color5  #EA76CB
color13 #EA76CB

# cyan
color6  #179299
color14 #179299

# white
color7  #ACB0BE
color15 #BCC0CC

